"""sprint1 onboarding answers

Adds `onboarding_answers` (server-owned questionnaire answers, upserted per user+question) and
scoring provenance columns on `psychological_profiles` (questionnaire_version, scored_at).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 13:45:02.424639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_onboarding_answers_user_question')
    )
    op.create_index(op.f('ix_onboarding_answers_user_id'), 'onboarding_answers', ['user_id'], unique=False)
    op.add_column('psychological_profiles', sa.Column('questionnaire_version', sa.String(length=32), nullable=True))
    op.add_column('psychological_profiles', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psychological_profiles', 'scored_at')
    op.drop_column('psychological_profiles', 'questionnaire_version')
    op.drop_index(op.f('ix_onboarding_answers_user_id'), table_name='onboarding_answers')
    op.drop_table('onboarding_answers')
    # ### end Alembic commands ###
